apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kfkv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-kfkv@sha256:5096b0acc66c285e8cc9365adc1728c22c6f8206695bc9042c31570c85a9246b
        name: my-nodejs
        resources: {}
status: {}
